routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\Blog\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PostController::class, 'index']);

Route::get('/test', function () {
    return view('welcome');
});

// Route::prefix('/articles')->name('blog.')->group(function () {

//     Route::get('/blog/{id}-{slug}', function (int $id, string $slug) {

//         return [
//             'id' => $id,
//             'slug' => $slug,
//         ];

//     })->where([
//         'id' => '[0-9]+',
//         'slug' => '[a-z0-9\-]+',
//     ])->name('show');

// });

Route::prefix('admin')->name('admin.')->group(function () {

    Route::resource('properties', PropertyController::class);

    Route::resource('options', OptionController::class);

});

app/Models/Option.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Option extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'about',
        'slug',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'name' => 'string',
        'about' => 'string',
    ];

    /**
     * Get the list of the properties that include this option
     *
     * @return BelongsToMany<Property>
     */
    public function properties() : BelongsToMany
    {
        return $this->belongsToMany(Property::class);
    }
}

app/Http/Controllers/Admin/OptionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\OptionFormRequest;
use App\Models\Option;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class OptionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        return view('admin.options.index', [
            'options' => Option::paginate(20),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $option = new Option();

        return view('admin.options.form', [
            'option' => $option,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(OptionFormRequest $request): RedirectResponse
    {
        $option = Option::create($request->validated());

        return to_route('admin.options.index')->with('option-added', 'Le bien a bien été ajouté');
    }

    /**
     * Display the specified resource.
     */
    public function show(Option $option)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Option $option): View
    {
        return view('admin.options.form', [
            'option' => $option,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(OptionFormRequest $request, Option $option): RedirectResponse
    {
        $option->update($request->validate());

        return to_route('admin.options.index')->with('option-edited', 'La commodité a bien été modifiée');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Option $option): RedirectResponse
    {
        $option->delete();

        return to_route('admin.options.index')->with('option-deleted', 'La commodité a bien été supprimée');
    }
}

resources/views/admin/options/form.blade.php
@extends('layouts.admin')

@section('title', $option->exists ? 'Editer la commodité' : 'Ajouter une commodité')

@section('content')

    <div class="d-flex justify-content-between align-items-center">

        <h1>@yield('title')</h1>

        <a href="{{ route('admin.options.index') }}" class="btn btn-default">Retour</a>

    </div>

    <form action="{{ route($option->exists ? 'admin.options.update' : 'admin.options.store', ['option' => $option]) }}">

        @csrf
        @method($option->exists ? 'PATCH' : 'POST')

        <div class="row">

            @include('shared.input', ['class' => 'col', 'label' => 'Titre', 'name' => 'name', 'value' => $option->name])

            @include('shared.input', ['class' => 'col', 'type' => 'textarea', 'name' => 'description', 'value' => $option->description])


        </div>

        <div>
            @if ($option->exists)
                <input type="submit" class="btn btn-warning" value="Modifier">
            @else
                <input type="submit" class="btn btn-success" value="Valider">
            @endif
        </div>


    </form>



@endsection

resources/views/admin/options/index.blade.php
@extends('layouts.admin')

@section('title', 'Tous les commodités')

@section('content')

    <div class="d-flex justify-content-between align-items-center">

        <h1>Les commodités</h1>

        <a href="#" class="btn btn-primary">Ajouter une commodité</a>

    </div>

    <table class="table table-striped">

        <thead>
            <tr>
                <td>Titre</td>
                <td>Description</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            @forelse ($options as $option)
                <tr>
                    <td>{{ $option->name }}</td>
                    <td>{{ $option->description }}</td>
                    <td>

                        <div class="d-flex gap-2 w-100 justify-content-end">

                            <a href="{{ route('admin.options.edit', $option) }}" class="btn btn-warning">
                                <i class="fa-solid fa-pen"></i>
                            </a>
                            <form action="{{ route('admin.options.destroy', $option) }}">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </form>

                        </div>

                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6"> Aucun bien disponible</td>
                </tr>
            @endforelse
        </tbody>

    </table>

    {{-- {{ $options->links() }} --}}

@endsection