routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\Blog\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PostController::class, 'index']);

Route::get('/test', function () {
    return view('welcome');
});

// Route::prefix('/articles')->name('blog.')->group(function () {

//     Route::get('/blog/{id}-{slug}', function (int $id, string $slug) {

//         return [
//             'id' => $id,
//             'slug' => $slug,
//         ];

//     })->where([
//         'id' => '[0-9]+',
//         'slug' => '[a-z0-9\-]+',
//     ])->name('show');

// });

Route::prefix('admin')->name('admin.')->group(function () {

    Route::resource('properties', PropertyController::class);

    Route::resource('options', OptionController::class);

});

app/Models/Property.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Property extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'slug',
        'quarter_id',
        'description',
        'surface',
        'rooms',
        'bedrooms',
        'floor',
        'price_ht',
        'price_ttc',
        'address',
        'is_rent',
        'is_sold',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'title' => 'string',
        'slug' => 'string',
        'description' => 'string',
        'surface' => 'integer',
        'rooms' => 'integer',
        'bedrooms' => 'integer',
        'floor' => 'integer',
        'price_ht' => 'integer',
        'price_ttc' => 'integer',
        'address' => 'integer',
        'is_rent' => 'boolean',
        'is_sold' => 'boolean',
    ];

    /**
     * Get the quarter that owns the property
     */
    public function quarter(): BelongsTo
    {
        return $this->belongsTo(Quarter::class);
    }

    /**
     * Get these options
     *
     * @return BelongsToMany<Option>
     */
    public function options() : BelongsToMany
    {
        return $this->belongsToMany(Option::class);
    }
}

app/Http/Controllers/Admin/PropertyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PropertyFormRequest;
use App\Models\Property;
use App\Models\Option;
use Illuminate\View\View;

class PropertyController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        return view('admin.properties.index', [
            'properties' => Property::orderBy('created_at', 'desc')->paginate(20),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $property = new Property();

        $property->fill([
            'surface' => 40,
            'rooms' => 2,
            'bedrooms' => 1,
            'floor' => 0,
            'quarter_id' => 1,
            'address' => 'Djorogobité 1',
        ]);

        return view('admin.properties.form', [
            'property' => $property,
            'options' => Option::pluck('name', 'id'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(PropertyFormRequest $request)
    {
        $property = Property::create($request->validated());
        $property->options()->sync($request->validated('options'));

        return to_route('admin.properties.index')->with('property-added', 'Le bien a bien été ajouté');
    }

    /**
     * Display the specified resource.
     */
    public function show(Property $property)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Property $property): View
    {
        return view('admin.properties.form', [
            'property' => $property,
            'options' => Option::pluck('name', 'id'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(PropertyFormRequest $request, Property $property)
    {
        $property->options()->sync($request->validated('options'));
        $property->update($request->validate());

        return to_route('admin.properties.index')->with('property-edited', 'Le bien a été modifié');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Property $property)
    {
        $property->delete();

        return to_route('admin.properties.index')->with('property-deleted', 'Le bien a bien été supprimé');
    }
}

resources/views/admin/properties/form.blade.php
@extends('layouts.admin')

@section('title', $property->exists ? 'Editer un bien' : 'Ajouter un bien')

@section('content')

    <div class="d-flex justify-content-between align-items-center">

        <h1>@yield('title')</h1>

        <a href="{{ route('admin.properties.index') }}" class="btn btn-default">Retour</a>

    </div>

    <form action="{{ route($property->exists ? 'admin.properties.update' : 'admin.properties.store', ['property' => $property]) }}">

        @csrf
        @method($property->exists ? 'PATCH' : 'POST')

        <div class="row">

            @include('shared.input', ['class' => 'col', 'label' => 'Titre', 'name' => 'title', 'value' => $property->title])

            <!-- Surface and price -->
            <div class="col row">

                @include('shared.input', ['class' => 'col', 'name' => 'surface', 'value' => $property->surface])

                @include('shared.input', ['class' => 'col', 'label' => 'Prix', 'name' => 'price_ttc', 'value' => $property->price_ttc])

            </div>

            @include('shared.input', ['class' => 'col', 'type' => 'textarea', 'name' => 'description', 'value' => $property->description])

            <!-- Rooms, bedrooms and floor -->
            <div class="row">

                @include('shared.input', ['class' => 'col', 'label' => 'Pièces', 'name' => 'rooms', 'value' => $property->rooms])

                @include('shared.input', ['class' => 'col', 'label' => 'Chambres', 'name' => 'bedrooms', 'value' => $property->bedrooms])

                @include('shared.input', ['class' => 'col', 'label' => 'Etages', 'name' => 'floor', 'value' => $property->floor ])

            </div>

            <!-- Location (quarter and address) -->
            <div class="row">

                @include('shared.input', ['class' => 'col', 'label' => 'Quartier', 'name' => 'quarter_id', 'value' => $property->quarter_id])

                @include('shared.input', ['class' => 'col', 'label' => 'Addresse', 'name' => 'address', 'value' => $property->address])

            </div>

            <!-- Status (rent or sold) and Options -->
            <div class="row">

                @include('shared.select', ['class' => 'col', 'label' => 'Commodités', 'name' => 'options', 'value' => $property->options()->pluck('id'), 'multiple' => true, 'options' => $options])

                @include('shared.checkbox', ['class' => 'col', 'label' => 'Loué', 'name' => 'is_rent', 'value' => $property->is_rent])

                @include('shared.checkbox', ['class' => 'col', 'label' => 'Vendu', 'name' => 'is_sold', 'value' => $property->is_sold])

            </div>

        </div>

        <div>
            @if ($property->exists)
                <input type="submit" class="btn btn-warning" value="Modifier">
            @else
                <input type="submit" class="btn btn-success" value="Valider">
            @endif
        </div>


    </form>



@endsection

resources/views/admin/properties/index.blade.php
@extends('layouts.admin')

@section('title', 'Tous le biens')

@section('content')

    <div class="d-flex justify-content-between align-items-center">

        <h1>Les biens</h1>

        <a href="#" class="btn btn-primary">Ajouter un bien</a>

    </div>

    <table class="table table-striped">

        <thead>
            <tr>
                <td>Titre</td>
                <td>Localisation</td>
                <td>Surface (m<sup>2</sup>)</td>
                <td>Prix de vente (F. CFA)</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            @forelse ($properties as $property)
                <tr>
                    <td>{{ $property->title }}</td>
                    <td>{{ $property->address .' '.$property->quarter->name }}</td>
                    <td>{{ $property->surface }}</td>
                    <td>{{ number_format($property->price_ttc, thousands_separator: '.') }}</td>
                    <td>

                        <div class="d-flex gap-2 w-100 justify-content-end">

                            <a href="{{ route('admin.properties.edit', $property) }}" class="btn btn-warning">
                                <i class="fa-solid fa-pen"></i>
                            </a>
                            <form action="{{ route('admin.properties.destroy', $property) }}">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </form>

                        </div>

                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6"> Aucun bien disponible</td>
                </tr>
            @endforelse
        </tbody>

    </table>

    {{-- {{ $properties->links() }} --}}

@endsection